name: ci
on: { push: { branches: [main] }, pull_request: {} }
jobs:
  self:
    uses: JakobMelchard/.github/.github/workflows/node.yml@main
    with:
      lint-cmd: ""
      check-cmd: npx tsc
      test-cmd: npm test
      e2e-cmd: npm run e2e
      browsers: true
