name: ci
on: { push: { branches: [main] }, pull_request: {} }
jobs:
  self:
    uses: JakobMelchard/.github/.github/workflows/node.yml@main
    with:
      lint-cmd: ""
      check-cmd: npx tsc
      test-cmd: npm test
      e2e-cmd: npm run e2e
      browsers: true
  consumers:
    needs: self
    uses: ./.github/workflows/consumers-e2e.yml
    with: { hx-ref: '${{ github.event.pull_request.head.sha || github.sha }}' }
    secrets: inherit
